version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-cmc-compose
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cmc_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cmc_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cmc-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-cmc
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - cmc-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  cmc-network:
    driver: bridge
