// <auto-generated />
using System;
using CMC.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CMC.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CMC.Domain.Entities.Control", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostTotalEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Coverage")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<decimal>("DeltaEalEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EvidenceWeight")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Freshness")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<bool>("Implemented")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LibraryControlId")
                        .HasColumnType("uuid");

                    b.Property<int>("Maturity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Score")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceId");

                    b.HasIndex("LibraryControlId");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "IsDeleted");

                    b.ToTable("Controls", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.ControlScenario", b =>
                {
                    b.Property<Guid>("ControlId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.HasKey("ControlId", "ScenarioId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ControlScenarios", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("RevenuePerYear")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Customers_IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Confidentiality")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAt");

                    b.HasIndex("CustomerId", "IsDeleted");

                    b.ToTable("Evidence", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.Framework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version");

                    b.ToTable("Frameworks", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.FrameworkIndustry", b =>
                {
                    b.Property<Guid>("FrameworkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IndustryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IndustryId1")
                        .HasColumnType("uuid");

                    b.HasKey("FrameworkId", "IndustryId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("IndustryId1");

                    b.ToTable("FrameworkIndustries", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.Industry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Industries", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.Joins.CustomerIndustry", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IndustryId")
                        .HasColumnType("uuid");

                    b.HasKey("CustomerId", "IndustryId");

                    b.HasIndex("IndustryId");

                    b.ToTable("CustomerIndustries", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapexEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("ExternalDays")
                        .HasColumnType("integer");

                    b.Property<int>("InternalDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("OpexYearEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name", "IsDeleted");

                    b.ToTable("LibraryControls", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryControlFramework", b =>
                {
                    b.Property<Guid>("LibraryControlId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrameworkId")
                        .HasColumnType("uuid");

                    b.HasKey("LibraryControlId", "FrameworkId");

                    b.HasIndex("FrameworkId");

                    b.ToTable("LibraryControlFrameworks", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryControlIndustry", b =>
                {
                    b.Property<Guid>("LibraryControlId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IndustryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IndustryId1")
                        .HasColumnType("uuid");

                    b.HasKey("LibraryControlId", "IndustryId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("IndustryId1");

                    b.ToTable("LibraryControlIndustries", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryControlScenario", b =>
                {
                    b.Property<Guid>("LibraryControlId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LibraryScenarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LibraryScenarioId1")
                        .HasColumnType("uuid");

                    b.HasKey("LibraryControlId", "LibraryScenarioId");

                    b.HasIndex("LibraryScenarioId");

                    b.HasIndex("LibraryScenarioId1");

                    b.ToTable("LibraryControlScenarios", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryControlTag", b =>
                {
                    b.Property<Guid>("LibraryControlId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TagId1")
                        .HasColumnType("uuid");

                    b.HasKey("LibraryControlId", "TagId");

                    b.HasIndex("TagId");

                    b.HasIndex("TagId1");

                    b.ToTable("LibraryControlTags", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AnnualFrequency")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<decimal>("ImpactPctRevenue")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("LibraryScenarios", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryScenarioIndustry", b =>
                {
                    b.Property<Guid>("LibraryScenarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IndustryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IndustryId1")
                        .HasColumnType("uuid");

                    b.HasKey("LibraryScenarioId", "IndustryId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("IndustryId1");

                    b.ToTable("LibraryScenarioIndustries", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryScenarioTag", b =>
                {
                    b.Property<Guid>("LibraryScenarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TagId1")
                        .HasColumnType("uuid");

                    b.HasKey("LibraryScenarioId", "TagId");

                    b.HasIndex("TagId");

                    b.HasIndex("TagId1");

                    b.ToTable("LibraryScenarioTags", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.ProvisionedControlMap", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LibraryControlId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ControlId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerId", "LibraryControlId", "ScenarioId");

                    b.HasIndex("ControlId")
                        .IsUnique();

                    b.HasIndex("LibraryControlId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ProvisionedControlMaps", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.ProvisionedScenarioMap", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LibraryScenarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.HasKey("CustomerId", "LibraryScenarioId");

                    b.HasIndex("LibraryScenarioId");

                    b.HasIndex("ScenarioId")
                        .IsUnique();

                    b.ToTable("ProvisionedScenarioMaps", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("Frozen")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("CustomerId", "IsDeleted");

                    b.HasIndex("DefinitionId", "PeriodStart", "PeriodEnd", "CustomerId")
                        .IsUnique()
                        .HasDatabaseName("UX_Reports_Def_Period_Cust")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Reports", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reports_Period", "\"PeriodEnd\" >= \"PeriodStart\"");
                        });
                });

            modelBuilder.Entity("CMC.Domain.Entities.ReportDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sections")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WindowDays")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "Name")
                        .IsUnique();

                    b.ToTable("ReportDefinitions", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.Revision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("Table", "AssetId", "CreatedAt");

                    b.ToTable("Revisions", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.RiskAcceptance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ControlId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("RiskAcceptedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ControlId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("CustomerId", "ControlId");

                    b.ToTable("RiskAcceptances", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AnnualFrequency")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<decimal>("ImpactPctRevenue")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LibraryScenarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LibraryScenarioId");

                    b.HasIndex("CustomerId", "IsDeleted");

                    b.HasIndex("CustomerId", "LibraryScenarioId")
                        .IsUnique()
                        .HasDatabaseName("UX_Scenarios_Cust_LibScenario")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Scenarios", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.ScenarioTag", b =>
                {
                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TagId1")
                        .HasColumnType("uuid");

                    b.HasKey("ScenarioId", "TagId");

                    b.HasIndex("TagId");

                    b.HasIndex("TagId1");

                    b.ToTable("ScenarioTags", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.ToDo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Assignee")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("ControlId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("DependsOnTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExternalDays")
                        .HasColumnType("integer");

                    b.Property<int>("InternalDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ControlId");

                    b.HasIndex("DependsOnTaskId");

                    b.HasIndex("ControlId", "DependsOnTaskId");

                    b.HasIndex("Status", "IsDeleted");

                    b.ToTable("ToDos", (string)null);
                });

            modelBuilder.Entity("CMC.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .IsUnicode(false)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Users_CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CMC.Domain.Entities.Control", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Customer", "Customer")
                        .WithMany("Controls")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Evidence", "Evidence")
                        .WithMany("Controls")
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMC.Domain.Entities.LibraryControl", "LibraryControl")
                        .WithMany()
                        .HasForeignKey("LibraryControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Evidence");

                    b.Navigation("LibraryControl");
                });

            modelBuilder.Entity("CMC.Domain.Entities.ControlScenario", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Control", "Control")
                        .WithMany("ScenarioLinks")
                        .HasForeignKey("ControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Scenario", "Scenario")
                        .WithMany("ControlLinks")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Control");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("CMC.Domain.Entities.FrameworkIndustry", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Framework", "Framework")
                        .WithMany("IndustryLinks")
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Industry", null)
                        .WithMany("FrameworkIndustries")
                        .HasForeignKey("IndustryId1");

                    b.Navigation("Framework");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("CMC.Domain.Entities.Joins.CustomerIndustry", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerIndustries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Industry", "Industry")
                        .WithMany("CustomerIndustries")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryControlFramework", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Framework", "Framework")
                        .WithMany("ControlLinks")
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.LibraryControl", "LibraryControl")
                        .WithMany("FrameworkLinks")
                        .HasForeignKey("LibraryControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Framework");

                    b.Navigation("LibraryControl");
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryControlIndustry", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Industry", null)
                        .WithMany("LibraryControlIndustries")
                        .HasForeignKey("IndustryId1");

                    b.HasOne("CMC.Domain.Entities.LibraryControl", "LibraryControl")
                        .WithMany("IndustryLinks")
                        .HasForeignKey("LibraryControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");

                    b.Navigation("LibraryControl");
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryControlScenario", b =>
                {
                    b.HasOne("CMC.Domain.Entities.LibraryControl", "LibraryControl")
                        .WithMany("ScenarioLinks")
                        .HasForeignKey("LibraryControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.LibraryScenario", "LibraryScenario")
                        .WithMany()
                        .HasForeignKey("LibraryScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.LibraryScenario", null)
                        .WithMany("ControlLinks")
                        .HasForeignKey("LibraryScenarioId1");

                    b.Navigation("LibraryControl");

                    b.Navigation("LibraryScenario");
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryControlTag", b =>
                {
                    b.HasOne("CMC.Domain.Entities.LibraryControl", "LibraryControl")
                        .WithMany("TagLinks")
                        .HasForeignKey("LibraryControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Tag", null)
                        .WithMany("LibraryControlTags")
                        .HasForeignKey("TagId1");

                    b.Navigation("LibraryControl");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryScenarioIndustry", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Industry", null)
                        .WithMany("LibraryScenarioIndustries")
                        .HasForeignKey("IndustryId1");

                    b.HasOne("CMC.Domain.Entities.LibraryScenario", "LibraryScenario")
                        .WithMany("IndustryLinks")
                        .HasForeignKey("LibraryScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");

                    b.Navigation("LibraryScenario");
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryScenarioTag", b =>
                {
                    b.HasOne("CMC.Domain.Entities.LibraryScenario", "LibraryScenario")
                        .WithMany("TagLinks")
                        .HasForeignKey("LibraryScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Tag", null)
                        .WithMany("LibraryScenarioTags")
                        .HasForeignKey("TagId1");

                    b.Navigation("LibraryScenario");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CMC.Domain.Entities.ProvisionedControlMap", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Control", null)
                        .WithMany()
                        .HasForeignKey("ControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.LibraryControl", null)
                        .WithMany()
                        .HasForeignKey("LibraryControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Scenario", null)
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CMC.Domain.Entities.ProvisionedScenarioMap", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.LibraryScenario", null)
                        .WithMany()
                        .HasForeignKey("LibraryScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Scenario", null)
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CMC.Domain.Entities.Report", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMC.Domain.Entities.ReportDefinition", null)
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CMC.Domain.Entities.ReportDefinition", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CMC.Domain.Entities.RiskAcceptance", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Control", null)
                        .WithMany()
                        .HasForeignKey("ControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CMC.Domain.Entities.Scenario", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.LibraryScenario", "LibraryScenario")
                        .WithMany()
                        .HasForeignKey("LibraryScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LibraryScenario");
                });

            modelBuilder.Entity("CMC.Domain.Entities.ScenarioTag", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Scenario", "Scenario")
                        .WithMany("TagLinks")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.Tag", null)
                        .WithMany("ScenarioTags")
                        .HasForeignKey("TagId1");

                    b.Navigation("Scenario");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CMC.Domain.Entities.ToDo", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Control", null)
                        .WithMany("ToDos")
                        .HasForeignKey("ControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMC.Domain.Entities.ToDo", null)
                        .WithMany()
                        .HasForeignKey("DependsOnTaskId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CMC.Domain.Entities.User", b =>
                {
                    b.HasOne("CMC.Domain.Entities.Customer", "Customer")
                        .WithMany("Users")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CMC.Domain.Entities.Control", b =>
                {
                    b.Navigation("ScenarioLinks");

                    b.Navigation("ToDos");
                });

            modelBuilder.Entity("CMC.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Controls");

                    b.Navigation("CustomerIndustries");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CMC.Domain.Entities.Evidence", b =>
                {
                    b.Navigation("Controls");
                });

            modelBuilder.Entity("CMC.Domain.Entities.Framework", b =>
                {
                    b.Navigation("ControlLinks");

                    b.Navigation("IndustryLinks");
                });

            modelBuilder.Entity("CMC.Domain.Entities.Industry", b =>
                {
                    b.Navigation("CustomerIndustries");

                    b.Navigation("FrameworkIndustries");

                    b.Navigation("LibraryControlIndustries");

                    b.Navigation("LibraryScenarioIndustries");
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryControl", b =>
                {
                    b.Navigation("FrameworkLinks");

                    b.Navigation("IndustryLinks");

                    b.Navigation("ScenarioLinks");

                    b.Navigation("TagLinks");
                });

            modelBuilder.Entity("CMC.Domain.Entities.LibraryScenario", b =>
                {
                    b.Navigation("ControlLinks");

                    b.Navigation("IndustryLinks");

                    b.Navigation("TagLinks");
                });

            modelBuilder.Entity("CMC.Domain.Entities.Scenario", b =>
                {
                    b.Navigation("ControlLinks");

                    b.Navigation("TagLinks");
                });

            modelBuilder.Entity("CMC.Domain.Entities.Tag", b =>
                {
                    b.Navigation("LibraryControlTags");

                    b.Navigation("LibraryScenarioTags");

                    b.Navigation("ScenarioTags");
                });
#pragma warning restore 612, 618
        }
    }
}
