# k8s/prod/seed-master-user.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: seed-master-user
  namespace: cmc-prod
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seeder
          # bleibt absichtlich auf :latest, der Workflow pusht latest direkt vorher
          image: ghcr.io/USERNAME/REPOSITORY:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "/opt/seed/seed.sh"]
          env:
            # wichtig: gleicher Name wie im Deployment
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: cmc-app-secret
                  key: connection
            - name: MASTER_MAIL
              valueFrom:
                secretKeyRef:
                  name: master-user
                  key: email
            - name: MASTER_PWHASH
              valueFrom:
                secretKeyRef:
                  name: master-user
                  key: passwordHash
            # explizit welche DLL gestartet werden soll
            - name: APP_DLL
              value: "/app/CMC.Web.dll"
          volumeMounts:
            - name: seed-script
              mountPath: /opt/seed
              readOnly: true
      volumes:
        - name: seed-script
          configMap:
            name: seed-master-user-script
            items:
              - key: seed.sh
                path: seed.sh
