apiVersion: v1
kind: ConfigMap
metadata:
  name: cmc-master-seed
  namespace: cmc-prod
data:
  seed.sql: |
    DO $$
    BEGIN
      -- Eindeutige Email für ON CONFLICT sicherstellen (nur falls noch nicht vorhanden)
      IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'public' AND indexname = 'idx_users_email_unique'
      ) THEN
        EXECUTE 'CREATE UNIQUE INDEX idx_users_email_unique ON "Users" ("Email")';
      END IF;

      -- Idempotenter Upsert. WICHTIG: PasswortHash wird fertig gehasht geliefert.
      INSERT INTO "Users"
      ("Id","Email","PasswordHash","FirstName","LastName","IsEmailConfirmed","CreatedAt","Department","Role")
      VALUES
      (
        :'uid'::uuid,
        :'email',
        :'pwdhash',
        :'first',
        :'last',
        TRUE,
        now(),
        :'dept',
        :'role'
      )
      ON CONFLICT ("Email") DO UPDATE
      SET
        "FirstName" = EXCLUDED."FirstName",
        "LastName"  = EXCLUDED."LastName",
        "IsEmailConfirmed" = TRUE,
        "Department" = EXCLUDED."Department",
        "Role" = EXCLUDED."Role",
        -- Passwort nur setzen, wenn aktuell leer
        "PasswordHash" = CASE
          WHEN COALESCE("Users"."PasswordHash",'') = '' THEN EXCLUDED."PasswordHash"
          ELSE "Users"."PasswordHash"
        END;
    END $$;
