apiVersion: v1
kind: ConfigMap
metadata:
  name: seed-master-user-script
  namespace: cmc-prod
data:
  seed.sh: |
    #!/bin/sh
    set -euo pipefail
    echo "[seed] starting…"
    echo "[seed] email=${MASTER_MAIL:-<unset>}"

    # 1) Falls self-contained Binary vorhanden
    BIN="$(find /app -maxdepth 1 -type f -perm -111 2>/dev/null | head -n1 || true)"

    # 2) Oder erste .dll greifen
    DLL="${APP_DLL:-}"
    [ -z "${DLL}" ] && DLL="$(ls /app/*.dll 2>/dev/null | head -n1 || true)"

    if [ -n "${BIN}" ]; then
      echo "[seed] running binary: ${BIN}"
      exec "${BIN}" seed-master-user
    elif [ -n "${DLL}" ]; then
      echo "[seed] running dotnet: ${DLL}"
      exec dotnet "${DLL}" seed-master-user
    else
      echo "[seed] ERROR: kein ausführbares Binary oder DLL in /app gefunden"
      ls -lah /app || true
      exit 1
    fi
