apiVersion: v1
kind: ConfigMap
metadata:
  name: seed-master-user-script
  namespace: cmc-prod
data:
  seed.sh: |
    #!/usr/bin/env sh
    set -eu
    echo "[seed] starting…"
    # Required envs:
    : "${CONNECTION_STRING:?missing}"
    : "${MASTER_MAIL:?missing}"
    : "${MASTER_PWHASH:?missing}"

    echo "[seed] email=${MASTER_MAIL}"

    # Beispiel: deine App übernimmt das Seeding via CLI/HTTP – hier CLI-Aufruf skizziert:
    # Passe den Pfad/Command an dein Image an.
    dotnet /app/Cmc.App.dll seed-master-user \
      --connection "$CONNECTION_STRING" \
      --email "$MASTER_MAIL" \
      --password-hash "$MASTER_PWHASH"

    echo "[seed] done."
