apiVersion: batch/v1
kind: Job
metadata:
  name: seed-master-user
  namespace: cmc-prod
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seeder
          # bleibt absichtlich auf :latest, weil der Workflow "latest" direkt vor dem Job pusht
          image: ghcr.io/USERNAME/REPOSITORY:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "/opt/seed/seed.sh"]
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: cmc-app-secret
                  key: connection
            - name: MASTER_MAIL
              valueFrom:
                secretKeyRef:
                  name: master-user
                  key: email
            - name: MASTER_PWHASH
              valueFrom:
                secretKeyRef:
                  name: master-user
                  key: passwordHash
          volumeMounts:
            - name: seed-script
              mountPath: /opt/seed
              readOnly: true
      volumes:
        - name: seed-script
          configMap:
            name: seed-master-user-script
            items:
              - key: seed.sh
                path: seed.sh
