apiVersion: v1
kind: Namespace
metadata:
  name: cmc-test
  labels:
    environment: test
---
apiVersion: v1
kind: Namespace
metadata:
  name: cmc-prod
  labels:
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: llm
  labels:
    environment: production
