name: Deploy CMC Test

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cmc_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build -c Release --verbosity normal
        env:
          ConnectionStrings__DefaultConnection: "Host=localhost;Database=cmc_test;Username=postgres;Password=postgres"

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    # Deploy nur für echte Branch-Pushes auf 'test', nicht für PRs:
    if: github.ref == 'refs/heads/test'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'src/CMC.Web/package-lock.json'

      - name: Install Frontend deps
        working-directory: src/CMC.Web
        run: npm ci
        # Falls kein package.json vorhanden:
        #   diesen Step löschen und im nächsten Step gepinnte npx-Variante verwenden.

      - name: Build Tailwind CSS
        working-directory: src/CMC.Web
        env:
          NODE_ENV: production
        run: |
          npx tailwindcss -c tailwind.config.js \
            -i ./Styles/app.css \
            -o ./wwwroot/style.css \
            -m
        # Alternative ohne npm ci:
        # run: |
        #   NODE_ENV=production npx --yes tailwindcss@3.4.10 \
        #     -c tailwind.config.js \
        #     -i ./Styles/app.css \
        #     -o ./wwwroot/style.css \
        #     -m

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test-latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Replace image name in manifests
        run: |
          sed -i "s|ghcr.io/USERNAME/REPOSITORY|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}|g" k8s/test/cmc-app.yaml

      - name: Create namespaces
        run: |
          kubectl apply -f k8s/namespaces.yaml

      - name: Create secrets
        env:
          DB_PASSWORD: ${{ secrets.DB_PW }}
        run: |
          # Postgres Secret
          kubectl -n cmc-test create secret generic postgres-secret \
            --from-literal=password="${DB_PASSWORD}" \
            --dry-run=client -o yaml | kubectl apply -f -

          # App Connection String Secret
          CONNECTION_STRING="Host=postgres;Port=5432;Database=cmc_test;Username=cmc_user;Password=${DB_PASSWORD};Pooling=true;SslMode=Disable;"
          kubectl -n cmc-test create secret generic cmc-app-secret \
            --from-literal=connection="${CONNECTION_STRING}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to test
        run: |
          kubectl apply -f k8s/test/

      - name: Wait for deployment
        run: |
          if kubectl -n cmc-test get deploy postgres >/dev/null 2>&1; then
            kubectl -n cmc-test rollout status deploy/postgres --timeout=600s
          else
            # Fallback, wenn es ein anderer Typ ist:
            kubectl wait --for=condition=available --timeout=600s deployment/postgres -n cmc-test || true
          fi
          kubectl -n cmc-test rollout status deploy/cmc-app --timeout=600s

      - name: Get service info
        run: |
          echo "Test deployment completed!"
          kubectl get pods -n cmc-test
          kubectl get services -n cmc-test
          echo "Access via: kubectl port-forward -n cmc-test service/cmc-app 8080:8080"
