name: Deploy CMC Test

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cmc_test
        options: >-
          --health-cmd "pg_isready -U postgres -d cmc_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build -c Release --verbosity normal
        env:
          ConnectionStrings__DefaultConnection: "Host=localhost;Database=cmc_test;Username=postgres;Password=postgres"

  build-and-deploy:
    needs: test
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Normalize image name
        run: echo "IMAGE_NAME_LOWER=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push test image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:test-latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Write kubeconfig from KUBECONFIG_B64 (single source of truth)
        shell: bash
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}
        run: |
          set -euo pipefail
          if [ -z "${KUBECONFIG_B64:-}" ]; then
            echo "Fehler: Secret KUBECONFIG_B64 fehlt."
            exit 1
          fi
          mkdir -p ~/.kube
          echo "$KUBECONFIG_B64" | base64 -d > ~/.kube/config 2>/dev/null || {
            echo "Fehler: KUBECONFIG_B64 ist kein gültiges Base64 (einzeilig!)."
            exit 1
          }
          chmod 600 ~/.kube/config

          echo -n "Server in kubeconfig: "
          kubectl config view --minify --raw -o jsonpath='{.clusters[0].cluster.server}'; echo

          CA_TMP=/tmp/ca.crt
          kubectl config view --raw -o jsonpath='{.clusters[0].cluster.certificate-authority-data}' | base64 -d > "$CA_TMP" 2>/dev/null || true
          if [ -s "$CA_TMP" ]; then
            curl -fsS "$(kubectl config view --minify --raw -o jsonpath='{.clusters[0].cluster.server}')"'/version' --cacert "$CA_TMP" >/dev/null || {
              echo "ACHTUNG: TLS/CA-Problem zwischen kubeconfig und API-Server."
              exit 1
            }
          fi

          kubectl cluster-info

      - name: Replace image name in test manifests
        run: |
          sed -i "s|ghcr.io/USERNAME/REPOSITORY|${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}|g" k8s/test/cmc-app.yaml

      - name: Create namespaces
        run: kubectl apply -f k8s/namespaces.yaml

      - name: Create/update secrets (test)
        env:
          DB_PASSWORD: ${{ secrets.DB_PW }}
        run: |
          set -euo pipefail
          kubectl -n cmc-test create secret generic postgres-secret \
            --from-literal=password="${DB_PASSWORD}" \
            --dry-run=client -o yaml | kubectl apply -f -

          CONNECTION_STRING="Host=postgres;Port=5432;Database=cmc_test;Username=cmc_user;Password=${DB_PASSWORD};Pooling=true;SslMode=Disable;"
          kubectl -n cmc-test create secret generic cmc-app-secret \
            --from-literal=connection="${CONNECTION_STRING}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to test
        run: kubectl apply -f k8s/test/

      - name: Wait for rollout
        run: |
          if kubectl -n cmc-test get deployment postgres >/dev/null 2>&1; then
            kubectl -n cmc-test rollout status deployment/postgres --timeout=600s
          fi
          kubectl -n cmc-test rollout status deployment/cmc-app --timeout=600s

      - name: Show service info
        run: |
          kubectl get pods -n cmc-test
          kubectl get services -n cmc-test
          echo "Port-forward via: kubectl -n cmc-test port-forward service/cmc-app 8080:8080"
